package com.jiubang.ggheart.apps.desks.diy.pref;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 * 
 * @author guoyiqing
 * 
 */
public class PrefKeyMap {

	public static final String SP_BACKUP_PRIVATE = "backup_private_sp";
	public static final String SP_UNBACKUP_PRIVATE = "unbackup_private_sp";

	/**
	 * 存储旧的,迁移过来的Sp的key对应新sp的name
	 */
	public static final HashMap<String, String> OLD_KEY2NEW_NAME_MAP = new HashMap<String, String>();
	
	/**
	 * 存储新(V4.15up)的key
	 */
	public static final HashMap<String, String> NEW_KEY2NEW_NAME_MAP = new HashMap<String, String>();

	/**
	 * 旧的的key对应旧的sp的name
	 */
	public static final HashMap<String, String> OLD_KEY2OLD_NAME_MAP = new HashMap<String, String>();
	
	/**
	 * 备份的,需要迁移的旧的sp
	 */
	public static final List<String> BACKUP_SP_NAME_MIGRATE_LIST = new ArrayList<String>();
	
	/**
	 * 不备份的,需要迁移的旧的sp
	 */
	public static final List<String> UNBACKUP_SP_NAME_MIGRATE_LIST = new ArrayList<String>();
	
	static {
		
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_APPGAME_WIDGET_SHOW_MESSAGE);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_AUTOCHECK);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_COUNT_FIVE);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_DBEXCEPTION);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_DIY);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_ERRORREPORT);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_FACEBOOK_RECORD);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_GMAIL_ACCOUNT_SETTING);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_INSTALL_PREFS);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_NEEDTOADJUSTWALLPAPERDIMENSION);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_NEEDTODIALOG);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_NOTICATIONTIP);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_ORIENTATION_XY_FONT);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_ORIENTATION_XY_ICON);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_RANDOMDEVICEID);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_ROOTINFO);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_SEARCH_STATISTIC);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBACKUP_ZERO_SCREEN_SEARCH);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBAKUP_ADMOB_UTIL_SP);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBAKUP_PREFERENCE_GORECOMM_WIDGE);
		UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBAKUP_STATISTICSUSERCOMMON);
		//UNBACKUP_SP_NAME_MIGRATE_LIST.add(PrefConst.SP_UNBAKUP_PREFERENCE_PROMOTION_CONFIG);
		
		
		/**-------------------------------旧的key,新的sp名-------------------**/
		/**-------------------------------旧的key,新的sp名-------------------**/
		/**-------------------------------旧的key,新的sp名-------------------**/
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_WIFI,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_MOBIDATA,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_TETHER_ICS,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_TETHER,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_BLUETOOTH,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_SCREENLOCK,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_DISPLAY,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_RINGTONE,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_LANGUAGE,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_APPINFO,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_STORAGE,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_BATTERY,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_DATAUSAGE_ICS,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_DATAUSAGE,
				SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_REQUEST_GORECOMM_WIDGET_DATA_SUCCESS_TIME,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_REQUEST_GORECOMM_WIDGET_DATA_FAILURE_TIME,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_START_REQUEST_GORECOMM_WIDGET_DATA_TIME,
				SP_UNBACKUP_PRIVATE);
		
		
		
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_TIMESTAMP, SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_USER_IS_COVER, SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_NEWSHOWDIALOG, SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP
				.put(PrefConst.KEY_ROOT_INFO_DATA, SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_HAS_SHOW_MESSAGE,
				SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_LONG_MENU, SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SEARCH_KEY, SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_WIDGET_SEARCH_KEY,
				SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_REFERRER_INFO_STORE_FLAG,
				SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(
				PrefConst.KEY_NEEDTOADJUSTWALLPAPERDIMENSIONVALUE,
				SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_MESSAGE_CENTER_SWITCH,
				SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_ACCOUNT, SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_PASSWORD, SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_LANGUAGE, SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_RANDOM_DEVICE_ID,
				SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_FIRST_HANDLE_APPUPDATE_MSG,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_CHECK, SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_CHECK_TIME, SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_UPLOAD, SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_NEEDSHOWTIP, SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_STARTTIME, SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SCREEN_COUNT, SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_NEED_TO_SEND_DB,
				SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_REPORT, SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_COUNT_FIVE, SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_ICON_INITIA_X,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_ICON_INITIA_Y,
				PrefConst.SP_UNBACKUP_ORIENTATION_XY_ICON);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_FONT_COLOR, SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_ZERO_SCREEN_SEARCH_HISTORY_WORDS,
				SP_UNBACKUP_PRIVATE);

		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_ICON_INITIA_Y,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_ICON_INITIA_X,
				SP_UNBACKUP_PRIVATE);
		OLD_KEY2NEW_NAME_MAP.put(PrefConst.KEY_ICON_COLOR, SP_UNBACKUP_PRIVATE);
		
		
		
		
		
		
		
		
		
		/**-----------------------------------以下为old2old---------------------------------------**/
		/**-----------------------------------以下为old2old---------------------------------------**/
		/**-----------------------------------以下为old2old---------------------------------------**/
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_WIFI,
				PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_MOBIDATA,
				PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_TETHER_ICS,
				PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_TETHER,
				PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_BLUETOOTH,
				PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_SCREENLOCK,
				PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_DISPLAY,
				PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_RINGTONE,
				PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_LANGUAGE,
				PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_APPINFO,
				PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_STORAGE,
				PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_BATTERY,
				PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_DATAUSAGE_ICS,
				PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SYSTEM_SETTING_DATAUSAGE,
				PrefConst.SP_UNBACKUP_SYSTEM_SETTING_PKG);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_REQUEST_GORECOMM_WIDGET_DATA_SUCCESS_TIME,
				PrefConst.SP_UNBAKUP_PREFERENCE_GORECOMM_WIDGE);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_REQUEST_GORECOMM_WIDGET_DATA_FAILURE_TIME,
				PrefConst.SP_UNBAKUP_PREFERENCE_GORECOMM_WIDGE);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_START_REQUEST_GORECOMM_WIDGET_DATA_TIME,
				PrefConst.SP_UNBAKUP_PREFERENCE_GORECOMM_WIDGE);
		
		
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_TIMESTAMP,
				PrefConst.SP_UNBAKUP_ADMOB_UTIL_SP);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_USER_IS_COVER,
				PrefConst.SP_UNBAKUP_STATISTICSUSERCOMMON);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_NEWSHOWDIALOG,
				PrefConst.SP_UNBACKUP_NEEDTODIALOG);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_ROOT_INFO_DATA,
				PrefConst.SP_UNBACKUP_ROOTINFO);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_HAS_SHOW_MESSAGE,
				PrefConst.SP_UNBACKUP_APPGAME_WIDGET_SHOW_MESSAGE);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_LONG_MENU,
				PrefConst.SP_UNBACKUP_SEARCH_STATISTIC);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SEARCH_KEY,
				PrefConst.SP_UNBACKUP_SEARCH_STATISTIC);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_WIDGET_SEARCH_KEY,
				PrefConst.SP_UNBACKUP_SEARCH_STATISTIC);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_REFERRER_INFO_STORE_FLAG,
				PrefConst.SP_UNBACKUP_INSTALL_PREFS);

		OLD_KEY2OLD_NAME_MAP.put(
				PrefConst.KEY_NEEDTOADJUSTWALLPAPERDIMENSIONVALUE,
				PrefConst.SP_UNBACKUP_NEEDTOADJUSTWALLPAPERDIMENSION);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_MESSAGE_CENTER_SWITCH,
				PrefConst.SP_UNBACKUP_FACEBOOK_RECORD);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_ACCOUNT,
				PrefConst.SP_UNBACKUP_GMAIL_ACCOUNT_SETTING);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_PASSWORD,
				PrefConst.SP_UNBACKUP_GMAIL_ACCOUNT_SETTING);

		OLD_KEY2OLD_NAME_MAP
				.put(PrefConst.KEY_LANGUAGE, PrefConst.SP_UNBACKUP_DIY);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_RANDOM_DEVICE_ID,
				PrefConst.SP_UNBACKUP_RANDOMDEVICEID);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_FIRST_HANDLE_APPUPDATE_MSG,
				PrefConst.SP_UNBACKUP_AUTOCHECK);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_CHECK,
				PrefConst.SP_UNBACKUP_AUTOCHECK);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_CHECK_TIME,
				PrefConst.SP_UNBACKUP_AUTOCHECK);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_UPLOAD,
				PrefConst.SP_UNBACKUP_AUTOCHECK);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_NEEDSHOWTIP,
				PrefConst.SP_UNBACKUP_NOTICATIONTIP);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_STARTTIME,
				PrefConst.SP_UNBACKUP_ERRORREPORT);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_SCREEN_COUNT,
				PrefConst.SP_UNBACKUP_ERRORREPORT);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_NEED_TO_SEND_DB,
				PrefConst.SP_UNBACKUP_ERRORREPORT);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_REPORT,
				PrefConst.SP_UNBACKUP_DBEXCEPTION);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_COUNT_FIVE,
				PrefConst.SP_UNBACKUP_COUNT_FIVE);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_ICON_INITIA_X,
				PrefConst.SP_UNBACKUP_ORIENTATION_XY_ICON);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_ICON_INITIA_Y,
				PrefConst.SP_UNBACKUP_ORIENTATION_XY_ICON);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_ICON_COLOR,
				PrefConst.SP_UNBACKUP_ORIENTATION_XY_ICON);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_ZERO_SCREEN_SEARCH_HISTORY_WORDS,
				PrefConst.SP_UNBACKUP_ZERO_SCREEN_SEARCH);

		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_FONT_INITIA_X,
				PrefConst.SP_UNBACKUP_ORIENTATION_XY_FONT);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_FONT_INITIA_Y,
				PrefConst.SP_UNBACKUP_ORIENTATION_XY_FONT);
		OLD_KEY2OLD_NAME_MAP.put(PrefConst.KEY_FONT_COLOR,
				PrefConst.SP_UNBACKUP_ORIENTATION_XY_FONT);
		
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SHOW_APP_LOCATE_TIPS, SP_UNBACKUP_PRIVATE);
		
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SLIDEMENU_SHOW_PROMOTION_AD, SP_UNBACKUP_PRIVATE);
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SLIDEMENU_SHOW_CLEAN_MASTER_AD_TIMESTAMP, SP_UNBACKUP_PRIVATE);
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SLIDEMENU_SHOW_DU_SPEED_TIMESTAMP, SP_UNBACKUP_PRIVATE);
		
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_HAS_RESTORE_FLAG, SP_UNBACKUP_PRIVATE);
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SCREEN_EDIT_APPS_ORDER_TYPE, SP_UNBACKUP_PRIVATE);
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_INSTALL_SHOW_NOTIFICATION, SP_UNBACKUP_PRIVATE);
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_GAME_FOLDER_ACCELERATE_SWITCH, SP_UNBACKUP_PRIVATE);
		
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_APP_ICON_CONFIG_SERVER_TIME_STAMP, SP_UNBACKUP_PRIVATE);
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_GAME_FOLDER_MODE, SP_UNBACKUP_PRIVATE);
		
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_LIGHTAPP_INFO_DOWNLODE_TIME, SP_UNBACKUP_PRIVATE);
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SMART_CARD_LESS_CREATE_TIME, SP_UNBACKUP_PRIVATE);
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_RECOMMEND_FOLD_HASHCODE, SP_UNBACKUP_PRIVATE);
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_RECOMMEND_GAME_HASHCODE, SP_UNBACKUP_PRIVATE);
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_APP_CLASSIFY_FIRST_TIME_AUTO_ARRAGEMENT, SP_UNBACKUP_PRIVATE);
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_SMART_CARD_GUIDE_PAGE_WEATHER_THE_SHOW, SP_UNBACKUP_PRIVATE);
		//激活码(需要备份到文件)
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_LAUNCHER_ACTIVATION_CODE_VALUE, SP_BACKUP_PRIVATE);
		//邀请入口标识(需要备份到文件)
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_LAUNCHER_ACTIVATION_INVITE_ENTR_FALG, SP_BACKUP_PRIVATE);
		//可邀请人数(需要备份到文件)
		NEW_KEY2NEW_NAME_MAP.put(PrefConst.KEY_LAUNCHER_ACTIVATION_INVITE_PEOPLE_NUMBER, SP_BACKUP_PRIVATE);
	}

}
